# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.sample_info import SampleInfo

class TestSampleInfo(unittest.TestCase):
    """SampleInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SampleInfo:
        """Test SampleInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SampleInfo`
        """
        model = SampleInfo()
        if include_optional:
            return SampleInfo(
                sample_id = '',
                name = '',
                sample_type = '',
                creation_date = 56,
                attributes = [
                    metaPyScape.models.sample_attribute.SampleAttribute(
                        name = '', 
                        value = '', )
                    ]
            )
        else:
            return SampleInfo(
        )
        """

    def testSampleInfo(self):
        """Test SampleInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
