# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.annotation_configuration import AnnotationConfiguration

class TestAnnotationConfiguration(unittest.TestCase):
    """AnnotationConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnotationConfiguration:
        """Test AnnotationConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnotationConfiguration`
        """
        model = AnnotationConfiguration()
        if include_optional:
            return AnnotationConfiguration(
                ions_for_reassignment = [
                    ''
                    ],
                main_ion_infos = [
                    metaPyScape.models.main_ion_details.MainIonDetails(
                        feature_id = '', 
                        main_ion_notation = '', 
                        mz = 1.337, 
                        may_reassign_primary_ion = True, 
                        retention_time_in_seconds = 1.337, 
                        ccs = 1.337, 
                        ms_spectrum = metaPyScape.models.ms_spectrum.MsSpectrum(
                            signals = [
                                metaPyScape.models.signal.Signal(
                                    mz = 1.337, 
                                    intensity = 1.337, 
                                    width = 1.337, )
                                ], 
                            analysis_id = '', 
                            mean_measured_mz = 1.337, 
                            rt_in_seconds = 1.337, 
                            ccs = 1.337, ), 
                        ms_ms_spectrum = metaPyScape.models.ms_ms_spectrum.MsMsSpectrum(), 
                        ms_ms_spectrum_deiso = metaPyScape.models.ms_ms_spectrum.MsMsSpectrum(), )
                    ]
            )
        else:
            return AnnotationConfiguration(
        )
        """

    def testAnnotationConfiguration(self):
        """Test AnnotationConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
