# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metaPyScape
from metaPyScape.models.aq_scores import AQScores  # noqa: E501
from metaPyScape.rest import ApiException


class TestAQScores(unittest.TestCase):
    """AQScores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAQScores(self):
        """Test AQScores"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metaPyScape.models.aq_scores.AQScores()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
