# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.model_meta_info import ModelMetaInfo

class TestModelMetaInfo(unittest.TestCase):
    """ModelMetaInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelMetaInfo:
        """Test ModelMetaInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelMetaInfo`
        """
        model = ModelMetaInfo()
        if include_optional:
            return ModelMetaInfo(
                id = '',
                name = '',
                version_number = '',
                available_ion_notations = [
                    ''
                    ],
                available_structure_types = [
                    'SMILES'
                    ]
            )
        else:
            return ModelMetaInfo(
        )
        """

    def testModelMetaInfo(self):
        """Test ModelMetaInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
