# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.sample_volume import SampleVolume

class TestSampleVolume(unittest.TestCase):
    """SampleVolume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SampleVolume:
        """Test SampleVolume
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SampleVolume`
        """
        model = SampleVolume()
        if include_optional:
            return SampleVolume(
                volume = 1.337,
                unit = ''
            )
        else:
            return SampleVolume(
        )
        """

    def testSampleVolume(self):
        """Test SampleVolume"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
