# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.feature_ion_ms_ms_spectrum_info import FeatureIonMsMsSpectrumInfo

class TestFeatureIonMsMsSpectrumInfo(unittest.TestCase):
    """FeatureIonMsMsSpectrumInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeatureIonMsMsSpectrumInfo:
        """Test FeatureIonMsMsSpectrumInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeatureIonMsMsSpectrumInfo`
        """
        model = FeatureIonMsMsSpectrumInfo()
        if include_optional:
            return FeatureIonMsMsSpectrumInfo(
                feature_id = '',
                feature_ion = metaPyScape.models.feature_ion.FeatureIon(
                    ion_notation = '', 
                    mz = 1.337, 
                    ccs = 1.337, 
                    id = '', 
                    main_ion = True, ),
                spectra = [
                    metaPyScape.models.ms_ms_spectrum.MsMsSpectrum(
                        signals = [
                            metaPyScape.models.signal.Signal(
                                mz = 1.337, 
                                intensity = 1.337, 
                                width = 1.337, )
                            ], )
                    ]
            )
        else:
            return FeatureIonMsMsSpectrumInfo(
        )
        """

    def testFeatureIonMsMsSpectrumInfo(self):
        """Test FeatureIonMsMsSpectrumInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
