# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metaPyScape
from metaPyScape.models.sample_info import SampleInfo  # noqa: E501
from metaPyScape.rest import ApiException


class TestSampleInfo(unittest.TestCase):
    """SampleInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSampleInfo(self):
        """Test SampleInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metaPyScape.models.sample_info.SampleInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
