# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.api.featuretable_api import FeaturetableApi


class TestFeaturetableApi(unittest.TestCase):
    """FeaturetableApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeaturetableApi()

    def tearDown(self) -> None:
        pass

    def test_add_flag_to_feature(self) -> None:
        """Test case for add_flag_to_feature

        Add Flag to Feature
        """
        pass

    def test_create_annotation(self) -> None:
        """Test case for create_annotation

        Create a custom annotation for a specific feature
        """
        pass

    def test_create_feature_table(self) -> None:
        """Test case for create_feature_table

        Create a new Feature Table based on a project file
        """
        pass

    def test_create_lipid_species_annotations_with_method(self) -> None:
        """Test case for create_lipid_species_annotations_with_method

        Create Lipid Species Annotations with Method
        """
        pass

    def test_create_smart_formula_annotations_with_method(self) -> None:
        """Test case for create_smart_formula_annotations_with_method

        Create SmartFormula Annotations with Method
        """
        pass

    def test_create_target_list_annotations_with_method(self) -> None:
        """Test case for create_target_list_annotations_with_method

        Create Target List Annotations with Method
        """
        pass

    def test_delete_annotation(self) -> None:
        """Test case for delete_annotation

        Delete a specific annotation for a specific feature
        """
        pass

    def test_generate_new_eics_and_eims(self) -> None:
        """Test case for generate_new_eics_and_eims

        Generate new EICs and EIMs for a specific Feature Table
        """
        pass

    def test_remove_flag_from_feature(self) -> None:
        """Test case for remove_flag_from_feature

        Remove Flag from Feature
        """
        pass

    def test_retrieve_annotation_configuration_by_id(self) -> None:
        """Test case for retrieve_annotation_configuration_by_id

        Retrieve Annotation Configuration by ID
        """
        pass

    def test_retrieve_annotation_methods_by_tool_id(self) -> None:
        """Test case for retrieve_annotation_methods_by_tool_id

        Retrieve Annotation Methods by Tool ID
        """
        pass

    def test_retrieve_eics_for_feature(self) -> None:
        """Test case for retrieve_eics_for_feature

        Retrieve EICs for a specific feature
        """
        pass

    def test_retrieve_eims_for_feature(self) -> None:
        """Test case for retrieve_eims_for_feature

        Retrieve EIMs for a specific feature
        """
        pass

    def test_retrieve_feature(self) -> None:
        """Test case for retrieve_feature

        Retrieve a specific Feature based on its ID
        """
        pass

    def test_retrieve_feature_ion_ms_spectra(self) -> None:
        """Test case for retrieve_feature_ion_ms_spectra

        Retrieve Feature Ion MS Spectra
        """
        pass

    def test_retrieve_feature_ms_ms_spectra(self) -> None:
        """Test case for retrieve_feature_ms_ms_spectra

        Retrieve Feature MS/MS Spectra
        """
        pass

    def test_retrieve_feature_ms_ms_spectra_deiso(self) -> None:
        """Test case for retrieve_feature_ms_ms_spectra_deiso

        Retrieve Feature MS/MS Deisotoped Spectra
        """
        pass

    def test_retrieve_feature_ms_spectra_details(self) -> None:
        """Test case for retrieve_feature_ms_spectra_details

        Retrieve Feature MS Spectra Details
        """
        pass

    def test_retrieve_feature_table(self) -> None:
        """Test case for retrieve_feature_table

        Fetches a specific Feature Table based on its ID
        """
        pass

    def test_retrieve_intensity_matrix(self) -> None:
        """Test case for retrieve_intensity_matrix

        Retrieve a intensity matrix of a Feature Table based on its ID
        """
        pass

    def test_save_new_annotation_configuration(self) -> None:
        """Test case for save_new_annotation_configuration

        Save a new Annotation Configuration for a specific Feature Table
        """
        pass


if __name__ == '__main__':
    unittest.main()
