# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.aq_scores import AQScores

class TestAQScores(unittest.TestCase):
    """AQScores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AQScores:
        """Test AQScores
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AQScores`
        """
        model = AQScores()
        if include_optional:
            return AQScores(
                mz_aq_score = 56,
                rt_aq_score = 56,
                isotope_pattern_aq_score = 56,
                msms_aq_score = 56,
                ccs_aq_score = 56,
                mz_deviation = 1.337,
                rt_deviation = 1.337,
                isotope_pattern_score = 1.337,
                msms_score = 1.337,
                ccs_deviation = 1.337,
                annotation_modifiers = [
                    ''
                    ]
            )
        else:
            return AQScores(
        )
        """

    def testAQScores(self):
        """Test AQScores"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
