# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.feature import Feature

class TestFeature(unittest.TestCase):
    """Feature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Feature:
        """Test Feature
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Feature`
        """
        model = Feature()
        if include_optional:
            return Feature(
                id = '',
                rt_in_seconds = 1.337,
                mass = 1.337,
                feature_ions = [
                    metaPyScape.models.feature_ion.FeatureIon(
                        ion_notation = '', 
                        mz = 1.337, 
                        ccs = 1.337, 
                        id = '', 
                        main_ion = True, )
                    ],
                primary_annotation = metaPyScape.models.annotation.Annotation(
                    id = '', 
                    name = '', 
                    formula = '', 
                    aq_scores = metaPyScape.models.aq_scores.AQScores(
                        mz_aq_score = 56, 
                        rt_aq_score = 56, 
                        isotope_pattern_aq_score = 56, 
                        msms_aq_score = 56, 
                        ccs_aq_score = 56, 
                        mz_deviation = 1.337, 
                        rt_deviation = 1.337, 
                        isotope_pattern_score = 1.337, 
                        msms_score = 1.337, 
                        ccs_deviation = 1.337, 
                        annotation_modifiers = [
                            ''
                            ], ), 
                    tool = '', 
                    structure_inchi = '', 
                    structure_smiles = '', 
                    database_identifiers = [
                        metaPyScape.models.database_identifier.DatabaseIdentifier(
                            label = '', 
                            identifier = '', )
                        ], 
                    annotated_ms_ms_fragment_details = [
                        metaPyScape.models.annotated_ms_ms_fragment_details.AnnotatedMsMsFragmentDetails(
                            fragment_ion_formula = '', 
                            accurate_mz = 1.337, 
                            ms_ms_spectrum_id = '', 
                            ms_ms_rule_type = '', 
                            lipid_identity_level = '', 
                            chain_information = '', )
                        ], ),
                all_annotations = [
                    metaPyScape.models.annotation.Annotation(
                        id = '', 
                        name = '', 
                        formula = '', 
                        aq_scores = metaPyScape.models.aq_scores.AQScores(
                            mz_aq_score = 56, 
                            rt_aq_score = 56, 
                            isotope_pattern_aq_score = 56, 
                            msms_aq_score = 56, 
                            ccs_aq_score = 56, 
                            mz_deviation = 1.337, 
                            rt_deviation = 1.337, 
                            isotope_pattern_score = 1.337, 
                            msms_score = 1.337, 
                            ccs_deviation = 1.337, 
                            annotation_modifiers = [
                                ''
                                ], ), 
                        tool = '', 
                        structure_inchi = '', 
                        structure_smiles = '', 
                        database_identifiers = [
                            metaPyScape.models.database_identifier.DatabaseIdentifier(
                                label = '', 
                                identifier = '', )
                            ], 
                        annotated_ms_ms_fragment_details = [
                            metaPyScape.models.annotated_ms_ms_fragment_details.AnnotatedMsMsFragmentDetails(
                                fragment_ion_formula = '', 
                                accurate_mz = 1.337, 
                                ms_ms_spectrum_id = '', 
                                ms_ms_rule_type = '', 
                                lipid_identity_level = '', 
                                chain_information = '', )
                            ], )
                    ],
                user_flags = [
                    'RED'
                    ]
            )
        else:
            return Feature(
        )
        """

    def testFeature(self):
        """Test Feature"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
