# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metaPyScape
from metaPyScape.api.projects_api import ProjectsApi  # noqa: E501
from metaPyScape.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project(self):
        """Test case for create_project

        Create a new project  # noqa: E501
        """
        pass

    def test_get_task_status(self):
        """Test case for get_task_status

        Get Task Status  # noqa: E501
        """
        pass

    def test_list_all_projects(self):
        """Test case for list_all_projects

        List All Projects  # noqa: E501
        """
        pass

    def test_retrieve_project(self):
        """Test case for retrieve_project

        Retrieve Project  # noqa: E501
        """
        pass

    def test_retrieve_project_info(self):
        """Test case for retrieve_project_info

        Retrieve Project Info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
