# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.database_identifier import DatabaseIdentifier

class TestDatabaseIdentifier(unittest.TestCase):
    """DatabaseIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseIdentifier:
        """Test DatabaseIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseIdentifier`
        """
        model = DatabaseIdentifier()
        if include_optional:
            return DatabaseIdentifier(
                label = '',
                identifier = ''
            )
        else:
            return DatabaseIdentifier(
        )
        """

    def testDatabaseIdentifier(self):
        """Test DatabaseIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
