# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.sample_attribute_type import SampleAttributeType

class TestSampleAttributeType(unittest.TestCase):
    """SampleAttributeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SampleAttributeType:
        """Test SampleAttributeType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SampleAttributeType`
        """
        model = SampleAttributeType()
        if include_optional:
            return SampleAttributeType(
                name = '',
                detailed_attribute_options = [
                    metaPyScape.models.sample_attribute_option.SampleAttributeOption(
                        name = '', 
                        color = metaPyScape.models.color.Color(
                            hex = '', 
                            name = '', ), 
                        symbol = 'CIRCLE', )
                    ]
            )
        else:
            return SampleAttributeType(
        )
        """

    def testSampleAttributeType(self):
        """Test SampleAttributeType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
