# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.api.samples_api import SamplesApi


class TestSamplesApi(unittest.TestCase):
    """SamplesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SamplesApi()

    def tearDown(self) -> None:
        pass

    def test_list_all_samples(self) -> None:
        """Test case for list_all_samples

        List All Samples
        """
        pass


if __name__ == '__main__':
    unittest.main()
