# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.project_info import ProjectInfo

class TestProjectInfo(unittest.TestCase):
    """ProjectInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectInfo:
        """Test ProjectInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectInfo`
        """
        model = ProjectInfo()
        if include_optional:
            return ProjectInfo(
                project_id = '',
                name = '',
                description = '',
                owner = '',
                experiments = [
                    metaPyScape.models.experiment_info.ExperimentInfo(
                        experiment_id = '', 
                        name = '', 
                        group_colors = '', 
                        group_symbols = '', 
                        creation_date = 56, 
                        samples = [
                            metaPyScape.models.sample_info.SampleInfo(
                                sample_id = '', 
                                name = '', 
                                sample_type = '', 
                                creation_date = 56, 
                                attributes = [
                                    metaPyScape.models.sample_attribute.SampleAttribute(
                                        name = '', 
                                        value = '', )
                                    ], )
                            ], )
                    ],
                creation_date = 56,
                attribute = [
                    metaPyScape.models.sample_attribute_type.SampleAttributeType(
                        name = '', 
                        detailed_attribute_options = [
                            metaPyScape.models.sample_attribute_option.SampleAttributeOption(
                                name = '', 
                                color = metaPyScape.models.color.Color(
                                    hex = '', 
                                    name = '', ), 
                                symbol = 'CIRCLE', )
                            ], )
                    ]
            )
        else:
            return ProjectInfo(
        )
        """

    def testProjectInfo(self):
        """Test ProjectInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
