# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metaPyScape.models.annotated_ms_ms_fragment_details import AnnotatedMsMsFragmentDetails

class TestAnnotatedMsMsFragmentDetails(unittest.TestCase):
    """AnnotatedMsMsFragmentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnotatedMsMsFragmentDetails:
        """Test AnnotatedMsMsFragmentDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnotatedMsMsFragmentDetails`
        """
        model = AnnotatedMsMsFragmentDetails()
        if include_optional:
            return AnnotatedMsMsFragmentDetails(
                fragment_ion_formula = '',
                accurate_mz = 1.337,
                ms_ms_spectrum_id = '',
                ms_ms_rule_type = '',
                lipid_identity_level = '',
                chain_information = ''
            )
        else:
            return AnnotatedMsMsFragmentDetails(
        )
        """

    def testAnnotatedMsMsFragmentDetails(self):
        """Test AnnotatedMsMsFragmentDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
