# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metaPyScape
from metaPyScape.models.feature_table import FeatureTable  # noqa: E501
from metaPyScape.rest import ApiException


class TestFeatureTable(unittest.TestCase):
    """FeatureTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeatureTable(self):
        """Test FeatureTable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metaPyScape.models.feature_table.FeatureTable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
