# coding: utf-8

"""
    MetaboScape REST Application

    Python Client to connect to a MetaboScape server (initially generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python3 setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "metaPyScape"
VERSION = "0.0.1"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="MetaboScape REST Application",
    author="Steffen Neumann",
    author_email="sneumann@ipb-halle.de",
    url="https://github.com/sneumann/metaPyScape",
    keywords=["OpenAPI", "OpenAPI-Generator", "MetaboScape REST Application"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache License",
    long_description_content_type='text/markdown',
    long_description="""\
    Python Client to connect to a MetaboScape server (initially generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    """,  # noqa: E501
    package_data={"metaPyScape": ["py.typed"]},
)