# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnnotationConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ions_for_reassignment': 'list[str]',
        'main_ion_infos': 'list[MainIonDetails]'
    }

    attribute_map = {
        'ions_for_reassignment': 'ionsForReassignment',
        'main_ion_infos': 'mainIonInfos'
    }

    def __init__(self, ions_for_reassignment=None, main_ion_infos=None):  # noqa: E501
        """AnnotationConfiguration - a model defined in Swagger"""  # noqa: E501
        self._ions_for_reassignment = None
        self._main_ion_infos = None
        self.discriminator = None
        if ions_for_reassignment is not None:
            self.ions_for_reassignment = ions_for_reassignment
        if main_ion_infos is not None:
            self.main_ion_infos = main_ion_infos

    @property
    def ions_for_reassignment(self):
        """Gets the ions_for_reassignment of this AnnotationConfiguration.  # noqa: E501


        :return: The ions_for_reassignment of this AnnotationConfiguration.  # noqa: E501
        :rtype: list[str]
        """
        return self._ions_for_reassignment

    @ions_for_reassignment.setter
    def ions_for_reassignment(self, ions_for_reassignment):
        """Sets the ions_for_reassignment of this AnnotationConfiguration.


        :param ions_for_reassignment: The ions_for_reassignment of this AnnotationConfiguration.  # noqa: E501
        :type: list[str]
        """

        self._ions_for_reassignment = ions_for_reassignment

    @property
    def main_ion_infos(self):
        """Gets the main_ion_infos of this AnnotationConfiguration.  # noqa: E501


        :return: The main_ion_infos of this AnnotationConfiguration.  # noqa: E501
        :rtype: list[MainIonDetails]
        """
        return self._main_ion_infos

    @main_ion_infos.setter
    def main_ion_infos(self, main_ion_infos):
        """Sets the main_ion_infos of this AnnotationConfiguration.


        :param main_ion_infos: The main_ion_infos of this AnnotationConfiguration.  # noqa: E501
        :type: list[MainIonDetails]
        """

        self._main_ion_infos = main_ion_infos

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnnotationConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnnotationConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
