# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FeatureTable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'polarity': 'str',
        'processing_workflow': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'polarity': 'polarity',
        'processing_workflow': 'processingWorkflow'
    }

    def __init__(self, id=None, name=None, polarity=None, processing_workflow=None):  # noqa: E501
        """FeatureTable - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._polarity = None
        self._processing_workflow = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if polarity is not None:
            self.polarity = polarity
        if processing_workflow is not None:
            self.processing_workflow = processing_workflow

    @property
    def id(self):
        """Gets the id of this FeatureTable.  # noqa: E501


        :return: The id of this FeatureTable.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FeatureTable.


        :param id: The id of this FeatureTable.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this FeatureTable.  # noqa: E501


        :return: The name of this FeatureTable.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FeatureTable.


        :param name: The name of this FeatureTable.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def polarity(self):
        """Gets the polarity of this FeatureTable.  # noqa: E501


        :return: The polarity of this FeatureTable.  # noqa: E501
        :rtype: str
        """
        return self._polarity

    @polarity.setter
    def polarity(self, polarity):
        """Sets the polarity of this FeatureTable.


        :param polarity: The polarity of this FeatureTable.  # noqa: E501
        :type: str
        """

        self._polarity = polarity

    @property
    def processing_workflow(self):
        """Gets the processing_workflow of this FeatureTable.  # noqa: E501


        :return: The processing_workflow of this FeatureTable.  # noqa: E501
        :rtype: str
        """
        return self._processing_workflow

    @processing_workflow.setter
    def processing_workflow(self, processing_workflow):
        """Sets the processing_workflow of this FeatureTable.


        :param processing_workflow: The processing_workflow of this FeatureTable.  # noqa: E501
        :type: str
        """

        self._processing_workflow = processing_workflow

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FeatureTable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FeatureTable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
