# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FeatureIon(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ion_notation': 'str',
        'mz': 'float',
        'ccs': 'float',
        'id': 'str',
        'main_ion': 'bool'
    }

    attribute_map = {
        'ion_notation': 'ionNotation',
        'mz': 'mz',
        'ccs': 'ccs',
        'id': 'id',
        'main_ion': 'mainIon'
    }

    def __init__(self, ion_notation=None, mz=None, ccs=None, id=None, main_ion=None):  # noqa: E501
        """FeatureIon - a model defined in Swagger"""  # noqa: E501
        self._ion_notation = None
        self._mz = None
        self._ccs = None
        self._id = None
        self._main_ion = None
        self.discriminator = None
        if ion_notation is not None:
            self.ion_notation = ion_notation
        if mz is not None:
            self.mz = mz
        if ccs is not None:
            self.ccs = ccs
        if id is not None:
            self.id = id
        if main_ion is not None:
            self.main_ion = main_ion

    @property
    def ion_notation(self):
        """Gets the ion_notation of this FeatureIon.  # noqa: E501


        :return: The ion_notation of this FeatureIon.  # noqa: E501
        :rtype: str
        """
        return self._ion_notation

    @ion_notation.setter
    def ion_notation(self, ion_notation):
        """Sets the ion_notation of this FeatureIon.


        :param ion_notation: The ion_notation of this FeatureIon.  # noqa: E501
        :type: str
        """

        self._ion_notation = ion_notation

    @property
    def mz(self):
        """Gets the mz of this FeatureIon.  # noqa: E501


        :return: The mz of this FeatureIon.  # noqa: E501
        :rtype: float
        """
        return self._mz

    @mz.setter
    def mz(self, mz):
        """Sets the mz of this FeatureIon.


        :param mz: The mz of this FeatureIon.  # noqa: E501
        :type: float
        """

        self._mz = mz

    @property
    def ccs(self):
        """Gets the ccs of this FeatureIon.  # noqa: E501


        :return: The ccs of this FeatureIon.  # noqa: E501
        :rtype: float
        """
        return self._ccs

    @ccs.setter
    def ccs(self, ccs):
        """Sets the ccs of this FeatureIon.


        :param ccs: The ccs of this FeatureIon.  # noqa: E501
        :type: float
        """

        self._ccs = ccs

    @property
    def id(self):
        """Gets the id of this FeatureIon.  # noqa: E501


        :return: The id of this FeatureIon.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FeatureIon.


        :param id: The id of this FeatureIon.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def main_ion(self):
        """Gets the main_ion of this FeatureIon.  # noqa: E501


        :return: The main_ion of this FeatureIon.  # noqa: E501
        :rtype: bool
        """
        return self._main_ion

    @main_ion.setter
    def main_ion(self, main_ion):
        """Sets the main_ion of this FeatureIon.


        :param main_ion: The main_ion of this FeatureIon.  # noqa: E501
        :type: bool
        """

        self._main_ion = main_ion

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FeatureIon, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FeatureIon):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
