# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from metaPyScape.models.feature_ion import FeatureIon
from metaPyScape.models.mobilogram import Mobilogram
from typing import Optional, Set
from typing_extensions import Self

class FeatureEims(BaseModel):
    """
    FeatureEims
    """ # noqa: E501
    feature_ion: Optional[FeatureIon] = Field(default=None, alias="featureIon")
    eims: Optional[List[Optional[Mobilogram]]] = None
    __properties: ClassVar[List[str]] = ["featureIon", "eims"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureEims from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of feature_ion
        if self.feature_ion:
            _dict['featureIon'] = self.feature_ion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in eims (list)
        _items = []
        if self.eims:
            for _item_eims in self.eims:
                if _item_eims:
                    _items.append(_item_eims.to_dict())
            _dict['eims'] = _items
        # set to None if eims (nullable) is None
        # and model_fields_set contains the field
        if self.eims is None and "eims" in self.model_fields_set:
            _dict['eims'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureEims from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "featureIon": FeatureIon.from_dict(obj["featureIon"]) if obj.get("featureIon") is not None else None,
            "eims": [Mobilogram.from_dict(_item) for _item in obj["eims"]] if obj.get("eims") is not None else None
        })
        return _obj


