# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Sample(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'volume': 'SampleVolume',
        'attributes': 'list[SampleAttribute]',
        'analysis': 'list[Analysis]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'volume': 'volume',
        'attributes': 'attributes',
        'analysis': 'analysis'
    }

    def __init__(self, id=None, name=None, type=None, volume=None, attributes=None, analysis=None):  # noqa: E501
        """Sample - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._type = None
        self._volume = None
        self._attributes = None
        self._analysis = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if volume is not None:
            self.volume = volume
        if attributes is not None:
            self.attributes = attributes
        if analysis is not None:
            self.analysis = analysis

    @property
    def id(self):
        """Gets the id of this Sample.  # noqa: E501


        :return: The id of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Sample.


        :param id: The id of this Sample.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Sample.  # noqa: E501


        :return: The name of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Sample.


        :param name: The name of this Sample.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this Sample.  # noqa: E501


        :return: The type of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Sample.


        :param type: The type of this Sample.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def volume(self):
        """Gets the volume of this Sample.  # noqa: E501


        :return: The volume of this Sample.  # noqa: E501
        :rtype: SampleVolume
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this Sample.


        :param volume: The volume of this Sample.  # noqa: E501
        :type: SampleVolume
        """

        self._volume = volume

    @property
    def attributes(self):
        """Gets the attributes of this Sample.  # noqa: E501


        :return: The attributes of this Sample.  # noqa: E501
        :rtype: list[SampleAttribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Sample.


        :param attributes: The attributes of this Sample.  # noqa: E501
        :type: list[SampleAttribute]
        """

        self._attributes = attributes

    @property
    def analysis(self):
        """Gets the analysis of this Sample.  # noqa: E501


        :return: The analysis of this Sample.  # noqa: E501
        :rtype: list[Analysis]
        """
        return self._analysis

    @analysis.setter
    def analysis(self, analysis):
        """Sets the analysis of this Sample.


        :param analysis: The analysis of this Sample.  # noqa: E501
        :type: list[Analysis]
        """

        self._analysis = analysis

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Sample, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Sample):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
