# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Signal(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mz': 'float',
        'intensity': 'float',
        'width': 'float'
    }

    attribute_map = {
        'mz': 'mz',
        'intensity': 'intensity',
        'width': 'width'
    }

    def __init__(self, mz=None, intensity=None, width=None):  # noqa: E501
        """Signal - a model defined in Swagger"""  # noqa: E501
        self._mz = None
        self._intensity = None
        self._width = None
        self.discriminator = None
        if mz is not None:
            self.mz = mz
        if intensity is not None:
            self.intensity = intensity
        if width is not None:
            self.width = width

    @property
    def mz(self):
        """Gets the mz of this Signal.  # noqa: E501

        m/z value in Da  # noqa: E501

        :return: The mz of this Signal.  # noqa: E501
        :rtype: float
        """
        return self._mz

    @mz.setter
    def mz(self, mz):
        """Sets the mz of this Signal.

        m/z value in Da  # noqa: E501

        :param mz: The mz of this Signal.  # noqa: E501
        :type: float
        """

        self._mz = mz

    @property
    def intensity(self):
        """Gets the intensity of this Signal.  # noqa: E501

        absolute intensity  # noqa: E501

        :return: The intensity of this Signal.  # noqa: E501
        :rtype: float
        """
        return self._intensity

    @intensity.setter
    def intensity(self, intensity):
        """Sets the intensity of this Signal.

        absolute intensity  # noqa: E501

        :param intensity: The intensity of this Signal.  # noqa: E501
        :type: float
        """

        self._intensity = intensity

    @property
    def width(self):
        """Gets the width of this Signal.  # noqa: E501

        the peak width at the given m/z and intensity (can be 0 for MS/MS spectra)  # noqa: E501

        :return: The width of this Signal.  # noqa: E501
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this Signal.

        the peak width at the given m/z and intensity (can be 0 for MS/MS spectra)  # noqa: E501

        :param width: The width of this Signal.  # noqa: E501
        :type: float
        """

        self._width = width

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Signal, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Signal):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
