# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from metaPyScape.models.task_info import TaskInfo
from typing import Optional, Set
from typing_extensions import Self

class WorkflowTaskInfo(BaseModel):
    """
    WorkflowTaskInfo
    """ # noqa: E501
    workflow_task_id: Optional[StrictStr] = Field(default=None, alias="workflowTaskId")
    status: Optional[StrictStr] = None
    task_infos: Optional[List[Optional[TaskInfo]]] = Field(default=None, alias="taskInfos")
    __properties: ClassVar[List[str]] = ["workflowTaskId", "status", "taskInfos"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowTaskInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in task_infos (list)
        _items = []
        if self.task_infos:
            for _item_task_infos in self.task_infos:
                if _item_task_infos:
                    _items.append(_item_task_infos.to_dict())
            _dict['taskInfos'] = _items
        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if task_infos (nullable) is None
        # and model_fields_set contains the field
        if self.task_infos is None and "task_infos" in self.model_fields_set:
            _dict['taskInfos'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowTaskInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workflowTaskId": obj.get("workflowTaskId"),
            "status": obj.get("status"),
            "taskInfos": [TaskInfo.from_dict(_item) for _item in obj["taskInfos"]] if obj.get("taskInfos") is not None else None
        })
        return _obj


