# coding: utf-8

"""
    MetaboScape REST Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2025b
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkflowTaskInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'workflow_task_id': 'str',
        'status': 'str',
        'task_infos': 'list[TaskInfo]'
    }

    attribute_map = {
        'workflow_task_id': 'workflowTaskId',
        'status': 'status',
        'task_infos': 'taskInfos'
    }

    def __init__(self, workflow_task_id=None, status=None, task_infos=None):  # noqa: E501
        """WorkflowTaskInfo - a model defined in Swagger"""  # noqa: E501
        self._workflow_task_id = None
        self._status = None
        self._task_infos = None
        self.discriminator = None
        if workflow_task_id is not None:
            self.workflow_task_id = workflow_task_id
        if status is not None:
            self.status = status
        if task_infos is not None:
            self.task_infos = task_infos

    @property
    def workflow_task_id(self):
        """Gets the workflow_task_id of this WorkflowTaskInfo.  # noqa: E501


        :return: The workflow_task_id of this WorkflowTaskInfo.  # noqa: E501
        :rtype: str
        """
        return self._workflow_task_id

    @workflow_task_id.setter
    def workflow_task_id(self, workflow_task_id):
        """Sets the workflow_task_id of this WorkflowTaskInfo.


        :param workflow_task_id: The workflow_task_id of this WorkflowTaskInfo.  # noqa: E501
        :type: str
        """

        self._workflow_task_id = workflow_task_id

    @property
    def status(self):
        """Gets the status of this WorkflowTaskInfo.  # noqa: E501


        :return: The status of this WorkflowTaskInfo.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this WorkflowTaskInfo.


        :param status: The status of this WorkflowTaskInfo.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def task_infos(self):
        """Gets the task_infos of this WorkflowTaskInfo.  # noqa: E501


        :return: The task_infos of this WorkflowTaskInfo.  # noqa: E501
        :rtype: list[TaskInfo]
        """
        return self._task_infos

    @task_infos.setter
    def task_infos(self, task_infos):
        """Sets the task_infos of this WorkflowTaskInfo.


        :param task_infos: The task_infos of this WorkflowTaskInfo.  # noqa: E501
        :type: list[TaskInfo]
        """

        self._task_infos = task_infos

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowTaskInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowTaskInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
